version: '3'
services:
  express:
    image: lp-back
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=local
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./docker/volume/mongodb1:/data/db
