const MEASUREMENT_SOURCES = {
  APPLE_HEALTH: "appleHealth",
  GOOGLE_FIT: "googleFit",
};

const SLEEP_VALUES = {
  ASLEEP: "ASLEEP",
  AWAKE: "AWAKE",
  IN_BED: "IN_BED",
};

const MEASUREMENT_CODES = {
  SLEEP: "sleep",
  ACTIVITY: "activity",
};

const MINUTES_IN_DAY = 1440;

export { MEASUREMENT_SOURCES, SLEEP_VALUES, MINUTES_IN_DAY, MEASUREMENT_CODES };
